services:
  - type: web
    name: restaurant-bot
    env: python
    region: frankfurt # или ближайший регион
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: finance-db
          property: connectionString

databases:
  - name: finance-db
    databaseName: finance_db
    user: finance_user
